FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:ubt-v3

# kubuntu-desktop 273 MB # 7054 kB #plasma-desktop 已装
# https://github.com/ms-jpq/kde-in-docker/blob/daddy/base/bionic/Dockerfile #nautilus > dolphin
RUN apt.sh kubuntu-desktop dolphin konsole

RUN \
  # KDE环境: pavucontrol图标丑出天际
  rm -f /home/headless/Desktop/pavucontrol.desktop; \
  \
  sed -i "s/startfluxbox/startplasma-x11/g" /etc/systemd/system/de-start.service;

# HEADLESS

ENV \
  DISPLAY=":10"

# ENTRYPOINT ["/entry.sh"]
# CMD ["plasma_session"]